"""add display_name and avatar_url to user

Revision ID: e09623e513f5
Revises: 10184d02d473
Create Date: 2026-03-16 17:33:33.378715

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e09623e513f5"
down_revision: str | Sequence[str] | None = "10184d02d473"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("display_name", sa.String(length=100), nullable=True))
    op.add_column("user", sa.Column("avatar_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "avatar_url")
    op.drop_column("user", "display_name")
    # ### end Alembic commands ###
