"""add tos_accepted_at and tos_version to user

Revision ID: ffa6fc175c0f
Revises: e09623e513f5
Create Date: 2026-03-16 20:08:58.156256

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffa6fc175c0f"
down_revision: str | Sequence[str] | None = "e09623e513f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("tos_accepted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("user", sa.Column("tos_version", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "tos_version")
    op.drop_column("user", "tos_accepted_at")
    # ### end Alembic commands ###
